### ISSUE TITLE
0.3.0 breaks manual config setup

### ISSUE THREAD

**Issue by Cardo1** [rooi/homebridge-lightwaverf#48]
Just tried updating to 0.3.0 however the plugin fails to load as it seems to fail when loading up a manual config.  This is the error:

[27/03/2021, 23:36:34] [LightWaveRF] LightWaveRF Platform Plugin Version 0.3.0
[27/03/2021, 23:36:34] [LightWaveRF] Fetching LightWaveRF switches and dimmers...
(node:11935) UnhandledPromiseRejectionWarning: TypeError: this.log is not a function
    at new LightwaveRF (/usr/local/lib/node_modules/homebridge-lightwaverf/lib/lightwaverf.js:48:18)
    at getLights (/usr/local/lib/node_modules/homebridge-lightwaverf/index.js:167:25)
    at LightWaveRFPlatform.accessories (/usr/local/lib/node_modules/homebridge-lightwaverf/index.js:182:5)
    at /usr/local/lib/node_modules/homebridge/src/bridgeService.ts:529:24
    at new Promise (<anonymous>)
    at BridgeService.loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:523:12)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:139:36)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11935) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11935) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rooi** [comment]
Sorry Cardo1. This should be fixed in 0.3.1, just published

**Comment by Cardo1** [comment]
Working with 0.3.1.

Thanks!
